server:
  port: 8848
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: AIGOU_CONFIG
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cyz826587096/aigou_config.git
          username: cyz826587096
          password: aiqian7853913